version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ATTENDTOEVENT
  - ATTENDTOWORKSHOP
  - autoincrement
  - chilean
  - Conekta
  - cpus
  - CUIT
  - Culqi
  - datasource
  - ekoru
  - healthcheck
  - Khipu
  - KHIPU
  - nestjs
  - Niubiz
  - postgresql
  - STOREPURCHASE
  - subcategoría
  - Subcategoría
  - subcategorias
  - subcategorías
  - TIKTOK
  - Transbank
  - upcycled
  - Upcycling
  - UPCYCLING
  - uuid
  - Webpay
  - WEBPAY
  - WHATSAPP
ignoreWords: []
import: []
